name: express_car_cleaning_co
description: Mock mobile car washing and detailing app to schedule car washes.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  table_calendar: ^3.0.2
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^4.2.1
  provider: ^5.0.0
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_swiper: ^1.1.6
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  assets:
    - images/carLogo.jpg


  fonts:
    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn-Italic-VariableFont_wght.ttf
  uses-material-design: true

